# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-14 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
