version: '2'
services:
  web:
    image: "docker.io/zaplon/gabinet"
    working_dir: /app/
    ports:
     - "8080:8080"
    volumes:
     - ./:/app/:Z
     - ./docker/fonts/:/usr/local/share/fonts/
    links:
     - mysql
     - memcached
    environment:
      DJANGO_SETTINGS_MODULE: docker_settings
      LANG: "pl_PL.UTF-8"
      LANGUAGE: "pl_PL"
      QT_QPA_PLATFORM: "offscreen"
    command: uwsgi --http 0.0.0.0:9001 --module docker_wsgi_configuration_module
  mysql:
    image: "mysql"
    volumes:
     - ./gabinet_docker/dbs/:/var/lib/mysql
     - ./gabinet_docker/mysql/:/docker-entrypoint-initdb.d/
  elasticsearch:
    image: elasticsearch:6.5.1
  memcached:
    image: memcached
  selenium:
    image: selenium/standalone-chrome
