version: '2'
services:
  web:
    image: "docker.io/zaplon/gabinet"
    working_dir: /app/
    ports:
     - "8080:8080"
    volumes:
     - ./:/app/:Z
     - ./docker/fonts/:/usr/local/share/fonts/
    links:
     - mysql
     - memcached
    environment:
      DJANGO_SETTINGS_MODULE: docker_settings
      LANG: "pl_PL.UTF-8"
      LANGUAGE: "pl_PL"
      QT_QPA_PLATFORM: "offscreen"
    command: uwsgi --http 0.0.0.0:9001 --module docker_wsgi_configuration_module
  mysql:
    image: "mysql"
    volumes:
     - ./gabinet_docker/dbs/:/var/lib/mysql
     - ./gabinet_docker/mysql/:/docker-entrypoint-initdb.d/
  elasticsearch:
    image: elasticsearch:6.5.1
  nginx:
    image: nginx
    networks:
      default:
        aliases:
          - gabinet
    depends_on:
      - web
    volumes:
      - ./gabinet_docker/nginx/sites-enabled/:/etc/nginx/sites-enabled/
      - ./gabinet_docker/nginx/sites-available/:/etc/nginx/sites-available/
      - ./gabinet_docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./public/static/:/static/
      - ./public/media/:/media/
    ports:
      - "80:80"
      - "443:443"
  memcached:
    image: memcached
