version: '2'
services:
  web:
    image: "docker.io/zaplon/gabinet"
    working_dir: /app/
    ports:
     - "8080:8080"
    volumes:
     - ./:/app/:Z
     - ./docker/fonts/:/usr/local/share/fonts/
    links:
     - mysql
     - memcached
     - ezla
     - rabbitmq
     - redis
     - celery
    environment:
      DJANGO_SETTINGS_MODULE: docker_settings
      LANG: "pl_PL.UTF-8"
      LANGUAGE: "pl_PL"
      QT_QPA_PLATFORM: "offscreen"
    command: uwsgi --http 0.0.0.0:9001 --module docker_wsgi_configuration_module
  celery:
    image: "docker.io/zaplon/gabinet"
    working_dir: /app/
    links:
      - rabbitmq
      - mysql
      - redis
    volumes:
      - ./:/app/:Z
    environment:
      DJANGO_SETTINGS_MODULE: docker_settings
    command: [celery, worker, --app=gabinet.tasks, --concurrency=2, --loglevel=DEBUG]
    depends_on:
      - rabbitmq
  mysql:
    image: "mysql"
    volumes:
     - ./gabinet_docker/dbs/:/var/lib/mysql
     - ./gabinet_docker/mysql/:/docker-entrypoint-initdb.d/
  elasticsearch:
    image: elasticsearch:6.5.1
  memcached:
    image: memcached
  selenium:
    image: selenium/standalone-chrome
  ezla:
    build: microservices/ezla/
    ports:
      - "8090:9001"
    command: uwsgi --ini uwsgi.ini
  redis:
    image: redis
    container_name: cache
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    expose:
      - '6379'
    volumes:
      - ./gabinet_docker/redis:/bitnami/redis/data
  rabbitmq:
    image: rabbitmq:3.7.5-management
    expose:
      - '5672'
      - '15672'
    volumes:
      - ./gabinet_docker/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
    environment:
      RABBITMQ_ERLANG_COOKIE: 6085e2412b6fa88647466c6a81c0cea0
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /
  prescriptions:
    build: ./microservices/prescription/
    ports:
      - "80:8082" 
