version: '2'
services:
  web:
    image: "docker.io/zaplon/gabinet"
    ports:
     - "8080:8080"
    volumes:
     - ./:/app/:Z
    links:
     - mysql
    environment:
      LANG: pl_PL.UTF-8
      LC_ALL: pl_PL.UTF-8
    command: uwsgi --http 0.0.0.0:9001 --module docker_wsgi_configuration_module
  mysql:
    image: "mysql"
  elasticsearch:
    image: elasticsearch
  wkhtmltopdf:
    image: michaelperrin/wkhtmltopdf:latest
  nginx:
    image: nginx
    networks:
      default:
        aliases:
          - gabinet
    depends_on:
      - web
    volumes:
      - ./docker/nginx/sites-enabled/:/etc/nginx/sites-enabled/
      - ./docker/nginx/sites-available/:/etc/nginx/sites-available/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./public/static/:/static/
    ports:
      - "80:80"
      - "443:443"
