version: '2'
services:
  web:
    image: "zaplon/gabinet"
    ports:
     - "8080:8080"
    volumes:
     - ./:/app/:Z
    links:
     - mysql
    environment:
      LANG: pl_PL.UTF-8
      LC_ALL: pl_PL.UTF-8
  mysql:
    image: "mysql"
  elasticsearch:
    image: elasticsearch
  wkhtmltopdf:
    image: michaelperrin/wkhtmltopdf:latest
