version: '2'
services:
  web:
    environment:
      DJANGO_SETTINGS_MODULE: production_settings
      LANG: "pl_PL.UTF-8"
      LANGUAGE: "pl_PL"
      QT_QPA_PLATFORM: "offscreen"
    image: "docker.io/zaplon/gabinet"
    working_dir: /app/
    volumes:
     - ./:/app/:Z
    links:
     - mysql
     - memcached
    command: uwsgi --http 0.0.0.0:9001 --module docker_wsgi_configuration_module
  mysql:
    image: "mariadb"
    volumes:
     - ./docker/dbs/:/var/lib/mysql
     - ./docker/mysql/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_USER: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  elasticsearch:
    image: elasticsearch
  wkhtmltopdf:
    image: michaelperrin/wkhtmltopdf:latest
  nginx:
    image: nginx
    networks:
      default:
        aliases:
          - gabinet
    depends_on:
      - web
    volumes:
      - ./docker/nginx/sites-enabled/:/etc/nginx/sites-enabled/
      - ./docker/nginx/sites-available/:/etc/nginx/sites-available/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./public/static/:/static/
      - ./public/media/:/media/
      - ./frontend/:/frontend/
    ports:
      - "80:80"
      - "443:443"
  memcached:
    image: memcached
