version: '2'
services:
  web:
    environment:
      DJANGO_SETTINGS_MODULE: production_settings
      LANG: "pl_PL.UTF-8"
      LANGUAGE: "pl_PL"
      QT_QPA_PLATFORM: "offscreen"
    image: "docker.io/zaplon/gabinet"
    working_dir: /app/
    volumes:
     - ./:/app/:Z
    links:
     - mysql
     - memcached
     - redis
     - celery
     - rabbitmq
    command: uwsgi --http 0.0.0.0:9001 --module docker_wsgi_configuration_module
  mysql:
    image: "mariadb"
    volumes:
     - ./docker/dbs/:/var/lib/mysql
     - ./docker/mysql/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_USER: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  elasticsearch:
    image: elasticsearch:6.5.1
  nginx:
    image: nginx
    networks:
      default:
        aliases:
          - gabinet
    depends_on:
      - web
    volumes:
      - ./docker/nginx/sites-enabled/:/etc/nginx/sites-enabled/
      - ./docker/nginx/sites-available/:/etc/nginx/sites-available/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./public/static/:/static/
      - ./public/media/:/media/
      - ./frontend/:/frontend/
    ports:
      - "80:80"
      - "443:443"
  memcached:
    image: memcached
  celery:
    image: "docker.io/zaplon/gabinet"
    working_dir: /app/
    links:
      - rabbitmq
      - mysql
      - redis
    volumes:
      - ./:/app/:Z
    environment:
      DJANGO_SETTINGS_MODULE: production_settings
    command: [celery, worker, --app=gabinet.tasks, --concurrency=2, --loglevel=INFO]
    depends_on:
      - rabbitmq
  redis:
    image: redis
    container_name: cache
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    expose:
      - '6379'
    volumes:
      - ./gabinet_docker/redis:/bitnami/redis/data
  rabbitmq:
    image: rabbitmq:3.7.5-management
    expose:
      - '5672'
      - '15672'
    volumes:
      - ./gabinet_docker/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
    environment:
      RABBITMQ_ERLANG_COOKIE: 6085e2412b6fa88647466c6a81c0cea0
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /
  prescriptions:
    build: ./microservices/prescription/
    ports:
      - "8082:80"
    volumes:
      - ./public/media/certs/:/certs/:Z
    expose:
      - '80'
    environment:
      GABINET_ENV: dev
