# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(default='')),
                ('template', models.CharField(default='visit/tabs/default.html', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('visit_pdf', models.FileField(blank=True, null=True, upload_to='visits/')),
                ('attachments', models.ManyToManyField(related_name='attachments', to='visit.Attachment')),
                ('tabs', models.ManyToManyField(related_name='tabs', to='visit.Tab')),
            ],
        ),
    ]
