# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-19 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0021_doctor_specializations'),
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='tab',
            unique_together=set([('doctor', 'order')]),
        ),
    ]
