# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icd10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('desc', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Rozpoznanie',
                'verbose_name_plural': 'Rozpoznania',
            },
        ),
    ]
