# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0002_icd10'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='attachments',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
