# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-21 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0002_auto_20170519_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visittab',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
