# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0003_auto_20161223_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('text', models.CharField(max_length=1000)),
                ('key', models.CharField(blank=True, choices=[('CTRL+F1', 'ctrl+f1'), ('CTRL+F2', 'ctrl+f2')], max_length=8, null=True)),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='visit.Tab')),
            ],
        ),
        migrations.AlterField(
            model_name='visit',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
