# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-22 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0003_auto_20170521_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabparent',
            name='can_add_templates',
            field=models.BooleanField(default=False),
        ),
    ]
