# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-29 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0004_tabparent_can_add_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kolejno\u015b\u0107'),
        ),
    ]
