# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_recipe_specialization'),
        ('visit', '0004_auto_20161227_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='doctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='user_profile.Doctor'),
            preserve_default=False
        ),
        migrations.AlterField(
            model_name='template',
            name='key',
            field=models.CharField(blank=True, choices=[('CTRL+F1', 'ctrl+f1'), ('CTRL+F2', 'ctrl+f2')], max_length=8, null=True, verbose_name='Skr\xf3t'),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='template',
            name='tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='visit.Tab', verbose_name='Sekcja'),
        ),
        migrations.AlterField(
            model_name='template',
            name='text',
            field=models.CharField(max_length=1000, verbose_name='Tekst'),
        ),
        migrations.AlterField(
            model_name='template',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Tytu\u0142'),
        ),
    ]
