# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-28 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import visit.models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0005_auto_20170529_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabparent',
            name='template',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='tabs',
        ),
        migrations.RemoveField(
            model_name='visittab',
            name='body',
        ),
        migrations.RemoveField(
            model_name='visittab',
            name='name',
        ),
        migrations.AddField(
            model_name='tabparent',
            name='type',
            field=models.CharField(choices=[(visit.models.TabTypes('Pole tekstowe'), 'Pole tekstowe'), (visit.models.TabTypes('Rozpoznanie'), 'Rozpoznanie'), (visit.models.TabTypes('Leki'), 'Leki'), (visit.models.TabTypes('Notatki'), 'Notatki'), (visit.models.TabTypes('Skierowania'), 'Skierowania'), (visit.models.TabTypes('Nagranie wideo'), 'Nagranie wideo')], default=visit.models.TabTypes('Pole tekstowe'), max_length=16, verbose_name='Typ'),
        ),
        migrations.AddField(
            model_name='visittab',
            name='type',
            field=models.CharField(default='DEFAULT', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visittab',
            name='visit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='visit.Visit'),
            preserve_default=False,
        ),
    ]
