# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-30 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import visit.models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0006_auto_20180528_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tab',
            name='parent',
        ),
        migrations.AddField(
            model_name='tab',
            name='type',
            field=models.CharField(choices=[(visit.models.TabTypes('Pole tekstowe'), 'Pole tekstowe'), (visit.models.TabTypes('Rozpoznanie'), 'Rozpoznanie'), (visit.models.TabTypes('Leki'), 'Leki'), (visit.models.TabTypes('Notatki'), 'Notatki'), (visit.models.TabTypes('Skierowania'), 'Skierowania'), (visit.models.TabTypes('Nagranie wideo'), 'Nagranie wideo')], default=visit.models.TabTypes('Pole tekstowe'), max_length=16, verbose_name='Typ'),
        ),
        migrations.DeleteModel(
            name='TabParent',
        ),
    ]
