# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-06-19 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0007_auto_20180530_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='tabs',
        ),
        migrations.AddField(
            model_name='icd10',
            name='visits',
            field=models.ManyToManyField(related_name='icd_codes', to='visit.Visit'),
        ),
        migrations.AlterField(
            model_name='tab',
            name='type',
            field=models.CharField(choices=[('DEFAULT', 'Pole tekstowe'), ('ICD10', 'Rozpoznanie'), ('MEDICINES', 'Leki'), ('NOTES', 'Notatki'), ('SERVICES', 'Skierowania'), ('VIDEO', 'Nagranie wideo')], default='DEFAULT', max_length=16, verbose_name='Typ'),
        ),
    ]
