# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-11-10 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0008_auto_20180619_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab',
            name='type',
            field=models.CharField(choices=[('DEFAULT', 'Pole tekstowe'), ('ICD10', 'Rozpoznanie'), ('MEDICINES', 'Leki'), ('NOTES', 'Notatki'), ('SERVICES', 'Skierowania'), ('VIDEO', 'Nagranie wideo'), ('OCULIST', 'Okulista')], default='DEFAULT', max_length=16, verbose_name='Typ'),
        ),
    ]
