# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-11-25 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0009_auto_20181110_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab',
            name='type',
            field=models.CharField(choices=[('DEFAULT', 'Pole tekstowe'), ('ICD10', 'Rozpoznanie'), ('MEDICINES', 'Leki'), ('NOTES', 'Notatki'), ('VIDEO', 'Nagranie wideo'), ('OCULIST', 'Okulista'), ('EXAMINATIONS', 'Badania dodatkowe'), ('EXAMINATIONS2', 'Skierowania')], default='DEFAULT', max_length=16, verbose_name='Typ'),
        ),
    ]
