# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-03-16 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0012_auto_20190125_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['updated']},
        ),
    ]
