# Generated by Django 2.1.7 on 2019-05-25 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0013_auto_20190316_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcdToVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_text', models.CharField(blank=True, max_length=400)),
                ('icd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.Icd10')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.Visit')),
            ],
        ),
        migrations.AddField(
            model_name='icd10',
            name='visits_tmp',
            field=models.ManyToManyField(through='visit.IcdToVisit', to='visit.Visit'),
        ),
    ]
