# Generated by Django 2.1.7 on 2019-05-25 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0015_auto_20190525_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icd10',
            name='visits',
        ),
        migrations.RemoveField(
            model_name='icd10',
            name='visits_tmp',
        ),
    ]
