# Generated by Django 2.1.7 on 2019-05-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0016_auto_20190525_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='icd10',
            name='visits',
            field=models.ManyToManyField(related_name='icd_codes', through='visit.IcdToVisit', to='visit.Visit'),
        ),
    ]
