# Generated by Django 2.1.7 on 2020-01-01 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0017_icd10_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='visittab',
            name='tab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='visit.Tab'),
        ),
        migrations.AlterField(
            model_name='template',
            name='key',
            field=models.CharField(blank=True, choices=[('CTRL+F1', 'ctrl+f1'), ('CTRL+F2', 'ctrl+f2'), ('CTRL+F3', 'ctrl+f3'), ('CTRL+F4', 'ctrl+f4'), ('CTRL+F5', 'ctrl+f5'), ('CTRL+F6', 'ctrl+f6'), ('CTRL+F7', 'ctrl+f7'), ('CTRL+F8', 'ctrl+f8'), ('CTRL+F9', 'ctrl+f9'), ('CTRL+F10', 'ctrl+f10'), ('ALT+F1', 'ALT+F1'), ('ALT+F2', 'ALT+F2'), ('ALT+F3', 'ALT+F3'), ('ALT+F4', 'ALT+F4'), ('ALT+F5', 'ALT+F5'), ('ALT+F6', 'ALT+F6'), ('ALT+F7', 'ALT+F7'), ('ALT+F8', 'ALT+F8'), ('ALT+F9', 'ALT+F9'), ('ALT+F10', 'ALT+F10')], max_length=8, null=True, verbose_name='Skrót'),
        ),
        migrations.AlterField(
            model_name='template',
            name='tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='visit.Tab', verbose_name='Zakładka'),
        ),
    ]
