# Generated by Django 2.1.7 on 2020-01-06 16:15

from django.db import migrations


def adjust_tabs(apps, schema_editor):
    Doctor = apps.get_model('user_profile', 'Doctor')
    Tab = apps.get_model('visit', 'Tab')
    for d in Doctor.objects.all():
        Tab.objects.filter(doctor=d).update(order=123124)
        for i, tab in enumerate(d.tabs.all().order_by('order')):
            tab.order = i + 1
            tab.save()


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0018_auto_20200102_0054'),
    ]

    operations = [
        migrations.RunPython(adjust_tabs, migrations.RunPython.noop)
    ]
