# Generated by Django 2.1.7 on 2020-01-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0019_auto_20200106_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Kolejność'),
            preserve_default=False,
        ),
    ]
