# Generated by Django 2.1.7 on 2020-01-06 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0020_auto_20200106_1720'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tab',
            unique_together=set(),
        ),
    ]
