# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-10 10:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='AgreementToUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Added date')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agreements.Agreement', verbose_name='Agreements')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='U\u017cytkownik')),
            ],
        ),
        migrations.AddField(
            model_name='agreement',
            name='users',
            field=models.ManyToManyField(related_name='agreements', through='agreements.AgreementToUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
