# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-10 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
