# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-27 15:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agreements', '0002_agreement_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreement',
            options={'verbose_name': 'agreement', 'verbose_name_plural': 'agreements'},
        ),
        migrations.AlterModelOptions(
            name='agreementtouser',
            options={'verbose_name': 'user agreement', 'verbose_name_plural': 'users agreements'},
        ),
        migrations.AddField(
            model_name='agreement',
            name='targeted_users',
            field=models.ManyToManyField(blank=True, help_text='select users which should see the agreement.', related_name='user_agreements', to=settings.AUTH_USER_MODEL, verbose_name='targeted users'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Tekst'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='agreementtouser',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agreements.Agreement', verbose_name='Agreement'),
        ),
    ]
