# Generated by Django 2.1.7 on 2019-04-06 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0004_auto_20181110_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 4, 6, 21, 19, 13, 406412)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agreement',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='title',
            field=models.CharField(default=datetime.datetime(2019, 4, 6, 21, 19, 19, 520112), max_length=256, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
