# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_recipe_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='working_hours',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
