# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_doctor_visit_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='terms_generated_till',
            field=models.DateField(blank=True, null=True),
        ),
    ]
