# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_doctor_terms_generated_till'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='terms_end',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='terms_start',
            field=models.TimeField(default='09:00'),
        ),
    ]
