# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-07 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0016_auto_20170501_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Adres'),
        ),
    ]
