# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-17 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0019_auto_20170514_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Tytu\u0142'),
        ),
    ]
