# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-27 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0022_systemsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsettings',
            options={},
        ),
        migrations.AddField(
            model_name='profile',
            name='css',
            field=models.CharField(choices=[('classic', 'Klasyczny')], default='classic', max_length=20, verbose_name='Interfejs'),
        ),
    ]
