# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-29 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0023_auto_20170527_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='info',
            field=models.TextField(blank=True, help_text='Informacje pomocnicze o alergiach, przebytych zabiegach, etc...', null=True, verbose_name='Wa\u017cne informacje'),
        ),
    ]
