# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-29 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0024_patient_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsettings',
            options={'verbose_name': 'Ustawienia systemowe', 'verbose_name_plural': 'Ustawienia systemowe'},
        ),
    ]
