# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-29 19:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0025_auto_20170529_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='mobile',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numer kom\xf3rki'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='pwz',
            field=models.CharField(max_length=7, verbose_name='Numer PWZ'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specializations',
            field=models.ManyToManyField(related_name='doctors', to='user_profile.Specialization', verbose_name='Specializacje'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL, verbose_name='Lekarz'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='visit_duration',
            field=models.IntegerField(default=15, verbose_name='Czas trwania wizyty'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='working_hours',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Godziny pracy'),
        ),
    ]
