# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-30 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0026_auto_20170529_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='working_hours',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Godziny pracy'),
        ),
    ]
