# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-18 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0027_auto_20170530_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='logo',
            field=models.ImageField(upload_to='', verbose_name='Logo'),
        ),
    ]
