# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-28 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0028_auto_20180218_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
