# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-06-19 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0030_auto_20180602_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pesel',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='Pesel'),
        ),
    ]
