# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-09-03 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0031_auto_20180619_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Lekarz', 'verbose_name_plural': 'Lekarze'},
        ),
        migrations.AlterField(
            model_name='specialization',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='code_misal',
            field=models.CharField(max_length=100, verbose_name='Kod MISAL'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nazwa'),
        ),
    ]
