# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-11-10 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0032_auto_20180903_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
    ]
