# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-11-25 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0034_systemsettings_documents_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.CharField(max_length=30)),
                ('date_used', models.DateTimeField(null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='user_profile.Doctor')),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
