# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-01-25 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0035_auto_20181125_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='documents_header',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='documents_header_left',
            field=models.TextField(blank=True, verbose_name='Nagłówek dokumentów (lewa strona)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='documents_header_right',
            field=models.TextField(blank=True, verbose_name='Nagłówek dokumentów (prawa strona)'),
        ),
    ]
