# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-02-13 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0036_auto_20190125_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('doctor', 'Lekarz'), ('worker', 'Pracownik')], default='doctor', max_length=10),
            preserve_default=False,
        ),
    ]
