# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-03-16 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import g_utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0038_auto_20190220_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='show_weekends',
            field=models.BooleanField(default=False, verbose_name='Pokaż weekendy na kalendarzu'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='nip',
            field=models.CharField(blank=True, max_length=13, validators=[g_utils.validators.NIPValidator()], verbose_name='Numer NIP'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='regon',
            field=models.CharField(blank=True, max_length=14, validators=[g_utils.validators.REGONValidator()], verbose_name='Numer REGON'),
        ),
    ]
