# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-03-17 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0039_auto_20190316_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='css',
        ),
        migrations.AddField(
            model_name='profile',
            name='css_theme',
            field=models.CharField(choices=[('yeti', 'yeti'), ('minty', 'minty'), ('materia', 'materia')], default='yeti', max_length=10),
        ),
    ]
