# Generated by Django 2.1.7 on 2019-04-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0040_auto_20190317_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='css_theme',
            field=models.CharField(choices=[('yeti', 'Yeti'), ('minty', 'Minty'), ('materia', 'Materia')], default='yeti', max_length=10),
        ),
    ]
