# Generated by Django 2.1.7 on 2019-09-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0042_auto_20190721_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='nfz_department',
            field=models.CharField(default='07', max_length=2, verbose_name='Oddział NFZ'),
        ),
    ]
