# Generated by Django 2.1.7 on 2019-10-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0043_systemsettings_nfz_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Numer lokalu'),
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Miejscowość'),
        ),
        migrations.AddField(
            model_name='patient',
            name='postal_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='Kod pocztowy'),
        ),
        migrations.AddField(
            model_name='patient',
            name='second_name',
            field=models.CharField(default='', max_length=100, verbose_name='Drugie imię'),
        ),
        migrations.AddField(
            model_name='patient',
            name='street',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ulica'),
        ),
        migrations.AddField(
            model_name='patient',
            name='street_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Numer domu'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Miejscowość'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='street',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ulica'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='street_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Numer domu'),
        ),
    ]
