# Generated by Django 2.1.7 on 2019-11-11 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0044_auto_20191020_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFZSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rola_biznesowa', models.CharField(choices=[('LEKARZ_LEK_DENTYSTA_FELCZER', 'LEKARZ_LEK_DENTYSTA_FELCZER'), ('PIELEGNIARKA_POLOZNA', 'PIELEGNIARKA_POLOZNA')], default='LEKARZ_LEK_DENTYSTA_FELCZER', max_length=32)),
                ('certificate_tls', models.FileField(blank=True, null=True, upload_to='certs')),
                ('certificate_tls_password', models.CharField(blank=True, max_length=126)),
                ('certificate_wsse', models.FileField(blank=True, null=True, upload_to='certs')),
                ('certificate_wsse_password', models.CharField(blank=True, max_length=126)),
                ('certificate_user', models.FileField(blank=True, null=True, upload_to='certs')),
                ('certificate_user_password', models.CharField(blank=True, max_length=126)),
                ('id_podmiotu_oid_ext', models.CharField(blank=True, max_length=126)),
                ('id_podmiotu_lokalne', models.CharField(blank=True, max_length=126)),
                ('id_uzytkownika_oid_ext', models.CharField(blank=True, max_length=32)),
                ('id_miejsca_pracy_oid_ext', models.CharField(blank=True, max_length=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
