# Generated by Django 2.1.7 on 2019-11-11 17:18

from django.db import migrations


def create_nfz_settings(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    NFZSetting = apps.get_model('user_profile', 'NFZSettings')
    for u in User.objects.all():
        NFZSetting.objects.get_or_create(user=u)


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0045_nfzsettings'),
    ]

    operations = [
        migrations.RunPython(create_nfz_settings, migrations.RunPython.noop)
    ]
