# Generated by Django 2.1.7 on 2019-11-12 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0046_auto_20191111_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nfzsettings',
            old_name='id_uzytkownika_oid_ext',
            new_name='id_pracownika_oid_ext',
        ),
    ]
