# Generated by Django 2.1.7 on 2019-11-17 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0048_auto_20191117_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfzsettings',
            name='id_pracownika_oid_ext',
        ),
    ]
