# Generated by Django 2.1.7 on 2019-12-22 15:59
from django.core.management import call_command
from django.db import migrations


def add_permissions(apps, schema_editor):
    call_command('create_groups')


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0050_patient_birth_date'),
    ]

    operations = [
        migrations.RunPython(add_permissions, migrations.RunPython.noop)
    ]
