# Generated by Django 2.1.7 on 2019-12-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0052_auto_20191229_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfzsettings',
            name='id_podmiotu_oid_root',
            field=models.CharField(blank=True, default='2.16.840.1.113883.3.4424.2.4.68', max_length=126),
        ),
    ]
