# Generated by Django 2.1.7 on 2020-01-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0053_nfzsettings_id_podmiotu_oid_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfzsettings',
            name='id_podmiotu_oid_root',
            field=models.CharField(blank=True, max_length=126),
        ),
    ]
