# Generated by Django 2.1.7 on 2020-01-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0054_auto_20200102_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('doctor', 'Lekarz'), ('admin', 'Administrator'), ('registration', 'Rejestracja')], max_length=10),
        ),
    ]
