# Generated by Django 2.1.7 on 2020-01-08 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0055_auto_20200108_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_view_statistics', 'Can view statistics')]},
        ),
    ]
