# Generated by Django 2.1.7 on 2020-01-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0056_auto_20200108_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('doctor', 'Lekarz'), ('admin', 'Administrator'), ('registration', 'Rejestracja')], max_length=20),
        ),
    ]
