# Generated by Django 2.1.7 on 2020-01-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0057_auto_20200108_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Zostanie odczytana z numeru pesel, jeżeli pozostawiona pusta', null=True, verbose_name='Data urodzenia'),
        ),
    ]
