# Generated by Django 2.1.7 on 2020-01-18 20:47
from django.core.management import call_command
from django.db import migrations


def add_permissions(apps, schema_editor):
    call_command('create_groups')


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0058_auto_20200118_2147'),
    ]

    operations = [
        migrations.RunPython(add_permissions, migrations.RunPython.noop)
    ]
