# Generated by Django 2.1.7 on 2020-01-23 07:07
from django.db import migrations





class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0059_auto_20200118_2147'),
    ]

    operations = [
    ]
