# Generated by Django 2.1.7 on 2020-01-23 07:07
import re
from django.db import migrations


def fill_address_details(apps, schema_editor):
    Patient = apps.get_model('user_profile', 'Patient')
    for p in Patient.objects.filter(address__isnull=True):
        match = re.search(r'[^\W\d_]{3,}', p.address, re.UNICODE)
        if match and not p.street:
            p.street = match.group(0)
        if not p.city:
            p.city = p.address.split(' ')[-1]
        match = re.search(r'[0-9]{2}-[0-9]{3}', p.address)
        if match and not p.postal_code:
            p.postal_code = match.group(0)
        match = re.search(r'[0-9]{1,}', p.address)
        if match and not p.street_number:
            p.street_number = match.group(0)
        match = re.search(r'/[0-9]{1,}', p.address)
        if match and not p.apartment_number:
            p.apartment_number = match.group(0)[1:]
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0059_auto_20200118_2147'),
    ]

    operations = [
        migrations.RunPython(fill_address_details, migrations.RunPython.noop)
    ]
