# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-24 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={'permissions': (('edit_term', 'Mo\u017ce edytowa\u0107 terminy'),)},
        ),
    ]
