# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20161223_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'cancelled'), ('PENDING', 'pending'), ('FINISHED', 'finished')], default='PENDING', max_length=10),
        ),
    ]
