# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-24 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20170524_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={},
        ),
    ]
