# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-04 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0027_auto_20170530_2228'),
        ('timetable', '0003_auto_20170524_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adres')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Kod')),
            ],
            options={
                'verbose_name': 'Lokalizacja',
                'verbose_name_plural': 'Lokalizacje',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('price', models.FloatField(default=0, verbose_name='Cena')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Kod')),
                ('doctors', models.ManyToManyField(to='user_profile.Doctor', verbose_name='Lekarze')),
            ],
            options={
                'verbose_name': 'Us\u0142uga',
                'verbose_name_plural': 'Us\u0142ugi',
            },
        ),
        migrations.CreateModel(
            name='ServiceToDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Cena')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.Doctor', verbose_name='Lekarz')),
                ('localization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.Localization')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Service', verbose_name='Us\u0142uga')),
            ],
        ),
        migrations.AddField(
            model_name='term',
            name='localization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='timetable.Localization', verbose_name='Lokalizacja'),
        ),
        migrations.AddField(
            model_name='term',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='timetable.Service', verbose_name='Us\u0142uga'),
        ),
    ]
