# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20161227_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='visit.Visit'),
        ),
    ]
