# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-29 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0026_auto_20170529_1920'),
        ('timetable', '0003_auto_20170524_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('price', models.FloatField(default=0, verbose_name='Cena')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceToDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Cena')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.Doctor', verbose_name='Lekarz')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Service', verbose_name='Us\u0142uga')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='doctors',
            field=models.ManyToManyField(through='timetable.ServiceToDoctor', to='user_profile.Doctor', verbose_name='Lekarze'),
        ),
        migrations.AddField(
            model_name='term',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term', to='timetable.Service'),
        ),
    ]
