# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-29 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_auto_20170529_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adres')),
            ],
            options={
                'verbose_name': 'Lokalizacja',
                'verbose_name_plural': 'Lokalizacje',
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Us\u0142uga', 'verbose_name_plural': 'Us\u0142ugi'},
        ),
        migrations.AlterField(
            model_name='term',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='timetable.Service', verbose_name='Us\u0142uga'),
        ),
        migrations.AddField(
            model_name='servicetodoctor',
            name='localization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.Localization'),
        ),
        migrations.AddField(
            model_name='term',
            name='localization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='timetable.Localization', verbose_name='Lokalizacja'),
        ),
    ]
