# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-11-09 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_auto_20170604_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='doctors',
            field=models.ManyToManyField(blank=True, to='user_profile.Doctor', verbose_name='Lekarze'),
        ),
    ]
