# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_auto_20161228_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='user_profile.Patient'),
        ),
    ]
