# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20170102_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='user_profile.Patient', verbose_name='Pacjent'),
        ),
        migrations.AlterField(
            model_name='term',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'cancelled'), ('PENDING', 'pending'), ('FREE', 'free'), ('FINISHED', 'finished')], default='PENDING', max_length=10),
        ),
    ]
