# Generated by Django 2.1.7 on 2019-10-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20181109_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='color',
            field=models.CharField(blank=True, max_length=8, default='#5bc0de'),
        ),
    ]
