# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_auto_20170104_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'Anulowany'), ('PENDING', 'Oczekuj\u0105cy'), ('FREE', 'Wolny'), ('FINISHED', 'Zako\u0144czony')], default='PENDING', max_length=10),
        ),
    ]
