# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_auto_20170109_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='datetime',
            field=models.DateTimeField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='term',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='user_profile.Doctor', verbose_name='Lekarz'),
        ),
        migrations.AlterField(
            model_name='term',
            name='duration',
            field=models.IntegerField(default=15, verbose_name='Czas trwania (min)'),
        ),
    ]
