# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_auto_20170116_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='user_profile.Patient', verbose_name='Pacjent'),
        ),
        migrations.AlterField(
            model_name='term',
            name='visit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term', to='visit.Visit'),
        ),
    ]
