# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-26 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_auto_20170116_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
