# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('composition', models.TextField(blank=True, null=True)),
                ('form', models.TextField(blank=True, null=True)),
                ('dose', models.TextField(blank=True, null=True)),
                ('size', models.TextField(blank=True, null=True)),
                ('availability_cat', models.TextField(blank=True, null=True)),
                ('ean', models.CharField(blank=True, max_length=20, null=True)),
                ('mah', models.TextField(blank=True, null=True)),
                ('permission_nr', models.CharField(blank=True, max_length=20, null=True)),
                ('manufacturer', models.TextField(blank=True, null=True)),
                ('manufacturer_country', models.CharField(blank=True, max_length=3, null=True)),
                ('inn', models.TextField(blank=True, null=True)),
                ('importer', models.TextField(blank=True, null=True)),
                ('in_use', models.BooleanField(default=False)),
                ('refundation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Refundation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substance', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('size', models.CharField(blank=True, max_length=150, null=True)),
                ('ean', models.CharField(blank=True, max_length=20)),
                ('group', models.CharField(blank=True, max_length=200, null=True)),
                ('netto', models.CharField(blank=True, max_length=15, null=True)),
                ('brutto', models.CharField(blank=True, max_length=15, null=True)),
                ('detal', models.CharField(blank=True, max_length=15, null=True)),
                ('limit', models.CharField(blank=True, max_length=15, null=True)),
                ('recommendations', models.CharField(blank=True, max_length=400, null=True)),
                ('other_recommendations', models.CharField(blank=True, max_length=400, null=True)),
                ('to_pay', models.CharField(blank=True, max_length=10, null=True)),
                ('patient_price', models.CharField(blank=True, max_length=10, null=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refundations', to='medicine.Medicine')),
            ],
        ),
    ]
