# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('composition', models.TextField(blank=True, null=True)),
                ('manufacturer', models.TextField(blank=True, null=True)),
                ('manufacturer_country', models.CharField(blank=True, max_length=3, null=True)),
                ('permission_nr', models.CharField(blank=True, max_length=20, null=True)),
                ('form', models.TextField(blank=True, null=True)),
                ('mah', models.TextField(blank=True, null=True)),
                ('inn', models.TextField(blank=True, null=True)),
                ('importer', models.TextField(blank=True, null=True)),
                ('dose', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='dose',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='form',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='importer',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='inn',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='mah',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='manufacturer_country',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='name',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='permission_nr',
        ),
        migrations.AddField(
            model_name='medicine',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='medicine.MedicineParent'),
            preserve_default=False,
        ),
    ]
