# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-06-25 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_auto_20180624_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
