# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-09-03 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0032_auto_20180903_1831'),
        ('medicine', '0006_auto_20180625_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16)),
                ('date_used', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_numbers', to='user_profile.Doctor')),
            ],
        ),
        migrations.AddField(
            model_name='prescription',
            name='number_of_medicines',
            field=models.IntegerField(default=0),
        ),
    ]
