# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-11-17 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0007_auto_20180903_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineparent',
            name='manufacturer_country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
