# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-11-17 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0008_auto_20181117_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineparent',
            name='manufacturer_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
