# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-11-25 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0009_auto_20181117_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionnumber',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='PrescriptionNumber',
        ),
    ]
