# Generated by Django 2.1.7 on 2019-07-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0011_medicineparent_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='external_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicineparent',
            name='external_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        )
    ]
