# Generated by Django 2.1.7 on 2019-07-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0012_auto_20190720_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineparent',
            name='in_use',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='in_use',
            field=models.BooleanField(default=True),
        ),
    ]
