# Generated by Django 2.1.7 on 2019-08-25 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0014_auto_20190825_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='realisation_date',
            field=models.DateField(default=datetime.date(2019, 8, 25)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescription',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
