# Generated by Django 2.1.7 on 2019-08-25 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0015_auto_20190825_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinetoprescription',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medicines',
        ),
        migrations.AddField(
            model_name='medicinetoprescription',
            name='medicine_id',
            field=models.IntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicinetoprescription',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='medicine.Prescription'),
        ),
    ]
