# Generated by Django 2.1.7 on 2019-09-09 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0016_auto_20190825_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicineparent',
            options={'ordering': ('name',)},
        ),
    ]
