# Generated by Django 2.1.7 on 2019-10-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0017_auto_20190909_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='external_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
