# Generated by Django 2.1.7 on 2019-11-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0019_auto_20191109_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
