# Generated by Django 2.1.7 on 2019-11-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0021_medicinetoprescription_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='external_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='medicinetoprescription',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=64),
            preserve_default=False,
        ),
    ]
