# Generated by Django 2.1.7 on 2019-12-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0022_auto_20191123_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinetoprescription',
            name='refundation',
            field=models.CharField(blank=True, default='', max_length=10),
            preserve_default=False,
        ),
    ]
