# Generated by Django 2.1.7 on 2019-12-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0023_auto_20191208_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinetoprescription',
            name='composition',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicinetoprescription',
            name='medicine_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
