# Generated by Django 2.1.7 on 2019-12-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0024_auto_20191211_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
