# Generated by Django 2.1.7 on 2020-01-02 13:09
from django.core.management import call_command
from django.db import migrations, models


def load_medicines(apps, schema_editor):
    call_command('get_medicines', 'FULL')


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0026_auto_20191225_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineparent',
            name='external_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='external_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(load_medicines, migrations.RunPython.noop)
    ]
