# Generated by Django 2.1.7 on 2020-01-02 13:09
from django.core.management import call_command
from django.db import migrations, models


def load_medicines(apps, schema_editor):
    call_command('get_medicines', 'FULL')


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0027_auto_20200102_1409'),
    ]

    operations = [
        migrations.RunPython(load_medicines, migrations.RunPython.noop)
    ]
