# Generated by Django 2.1.7 on 2020-01-03 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0028_auto_20200102_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=128)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.Prescription')),
            ],
        ),
    ]
