# Generated by Django 2.1.7 on 2020-01-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0030_prescriptionjob_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinetoprescription',
            name='composition_name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
