# Generated by Django 2.1.7 on 2020-01-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0031_medicinetoprescription_composition_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineparent',
            name='refundation',
            field=models.BooleanField(default=False),
        ),
    ]
